info:
  contact: {}
paths:
  /test:
    get:
      description: 描述信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 测试接口
  /v1:
    get:
      description: This is a sample server Petstore server.
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"name","msg":"ok"}'
          schema:
            type: string
      summary: login
  /v1/user:
    get:
      description: this is user api
      responses:
        "200":
          description: '{"name": string, "message": string}'
          schema:
            type: json
      summary: user api
swagger: "2.0"
